<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Tekla.Structures.Plugins.PropertyPane" Version="2025.0.0" />
    <PackageReference Include="TeklaFusion" Version="4.1.10" />
  </ItemGroup>
</Project>