<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net48</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Tekla.Structures.Dialog" Version="2025.0.0" />
		<PackageReference Include="Tekla.Structures.Model" Version="2025.0.0" />
		<PackageReference Include="Tekla.Structures.Drawing" Version="2025.0.0" />
		<Content Include="Resources\*" />
    <Content Include="EllipsePlugin.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
	</ItemGroup>

</Project>