<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net48</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Tekla.Structures.Dialog" Version="2026.0.0" />
		<PackageReference Include="Tekla.Structures.Model" Version="2026.0.0" />
		<PackageReference Include="Tekla.Structures.Drawing" Version="2026.0.0" />
		<Content Include="Resources\*.bmp" />
		<PackageReference Include="TSAppConfigPatcherTask" Version="2.1.3" />
	</ItemGroup>

</Project>